version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/frontend/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/backend/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
